print("      AA        BBBBBBBBBBB")      
print("     A  A       BB         BB")
print("    A    A      BB         BB")
print("   AAAAAAAA     BBBBBBBBBBBBB")
print("  A        A    BB          BB")  
print(" A          A   BB          BB") 
print("A            A  BBBBBBBBBBBBB")
